models:
  - type: main
    engine: openai
    model: llama3.2:3b
    api_key_env_var: OPENAI_API_KEY
    parameters:
      base_url: http://host.docker.internal:11434/v1
      temperature: 0.0
      max_tokens: 64

rails:
  input:
    flows:
      - self check input
  output:
    flows:
      - self check output
